import { describe, it, expect, vi } from 'vitest';
import { finalizeWithCompilerGates, PrdCompilerQualityError } from '../server/prdCompilerFinalizer';
import type { CompilePrdResult } from '../server/prdCompiler';

function usage(total: number) {
  return {
    prompt_tokens: Math.floor(total / 2),
    completion_tokens: total - Math.floor(total / 2),
    total_tokens: total,
  };
}

describe('prdCompilerFinalizer excessive fallback review guard', () => {
  it('blocks fallback-heavy improve output at content review after targeted refinement attempts', async () => {
    const content = [
      '## System Vision',
      'A sprint planning workspace for agile delivery teams.',
      '',
      '## System Boundaries',
      'Web application for sprint planning and board management.',
      '',
      '## Domain Model',
      '- Sprint, Task, Team, Board.',
      '',
      '## Global Business Rules',
      '- Sprint goals must be approved before execution begins.',
      '',
      '## Functional Feature Catalogue',
      '',
      '### F-01: Sprint Board',
      '1. Purpose',
      'Coordinate sprint work on a shared board.',
      '10. Acceptance Criteria',
      '- Teams can move tasks between workflow columns.',
      '',
      '## Non-Functional Requirements',
      '- Board updates render within one second.',
      '',
      '## Error Handling & Recovery',
      '- Conflicts show retry guidance.',
      '',
      '## Deployment & Infrastructure',
      '- Node service with PostgreSQL.',
      '',
      '## Definition of Done',
      '- QA review and passing tests are required.',
      '',
      '## Out of Scope',
      '- No mobile app in this release.',
      '',
      '## Timeline & Milestones',
      '- Phase 1 delivers backlog import; Phase 2 delivers automation.',
      '',
      '## Success Criteria & Acceptance Testing',
      '- Planning time stays below twenty minutes per sprint.',
    ].join('\n');

    const compiled: CompilePrdResult = {
      content,
      structure: {
        systemVision: 'A sprint planning workspace for agile delivery teams.',
        systemBoundaries: 'Web application for sprint planning and board management.',
        domainModel: '- Sprint, Task, Team, Board.',
        globalBusinessRules: '- Sprint goals must be approved before execution begins.',
        features: [{
          id: 'F-01',
          name: 'Sprint Board',
          rawContent: '### F-01: Sprint Board\n1. Purpose\nCoordinate sprint work on a shared board.\n10. Acceptance Criteria\n- Teams can move tasks between workflow columns.',
          purpose: 'Coordinate sprint work on a shared board.',
          acceptanceCriteria: ['Teams can move tasks between workflow columns.'],
        }],
        nonFunctional: '- Board updates render within one second.',
        errorHandling: '- Conflicts show retry guidance.',
        deployment: '- Node service with PostgreSQL.',
        definitionOfDone: '- QA review and passing tests are required.',
        outOfScope: '- No mobile app in this release.',
        timelineMilestones: '- Phase 1 delivers backlog import; Phase 2 delivers automation.',
        successCriteria: '- Planning time stays below twenty minutes per sprint.',
        otherSections: {},
      },
      quality: {
        valid: true,
        truncatedLikely: false,
        missingSections: [],
        featureCount: 1,
        issues: [{ severity: 'warning', code: 'excessive_fallback_sections', message: '11/11 sections were auto-generated by the compiler.' }],
        fallbackSections: ['systemBoundaries', 'domainModel', 'globalBusinessRules', 'nonFunctional', 'errorHandling', 'deployment', 'definitionOfDone', 'outOfScope', 'timelineMilestones', 'successCriteria'],
      },
    };

    const compileDocument = vi.fn(() => compiled);

    let capturedError: unknown;

    try {
      await finalizeWithCompilerGates({
        initialResult: { content, model: 'mock/initial', usage: usage(80) },
        mode: 'improve',
        existingContent: content,
        language: 'en',
        originalRequest: 'Tighten an agile sprint planning PRD.',
        repairReviewer: async () => ({ content, model: 'mock/repair', usage: usage(10) }),
        contentRefineReviewer: async () => ({ content, model: 'mock/refine', usage: usage(10) }),
        compileDocument,
      });
    } catch (error) {
      capturedError = error;
    }

    expect(capturedError).toBeInstanceOf(PrdCompilerQualityError);
    expect(capturedError).toMatchObject({
      failureStage: 'content_review',
    });
    expect(compileDocument).toHaveBeenCalledTimes(2);
  });

  it('blocks the same fallback-heavy output earlier in compiler repair for generate mode', async () => {
    const content = [
      '## System Vision',
      'A sprint planning workspace for agile delivery teams.',
      '',
      '## System Boundaries',
      'Web application for sprint planning and board management.',
      '',
      '## Domain Model',
      '- Sprint, Task, Team, Board.',
      '',
      '## Global Business Rules',
      '- Sprint goals must be approved before execution begins.',
      '',
      '## Functional Feature Catalogue',
      '',
      '### F-01: Sprint Board',
      '1. Purpose',
      'Coordinate sprint work on a shared board.',
      '10. Acceptance Criteria',
      '- Teams can move tasks between workflow columns.',
      '',
      '## Non-Functional Requirements',
      '- Board updates render within one second.',
      '',
      '## Error Handling & Recovery',
      '- Conflicts show retry guidance.',
      '',
      '## Deployment & Infrastructure',
      '- Node service with PostgreSQL.',
      '',
      '## Definition of Done',
      '- QA review and passing tests are required.',
      '',
      '## Out of Scope',
      '- No mobile app in this release.',
      '',
      '## Timeline & Milestones',
      '- Phase 1 delivers backlog import; Phase 2 delivers automation.',
      '',
      '## Success Criteria & Acceptance Testing',
      '- Planning time stays below twenty minutes per sprint.',
    ].join('\n');

    const compiled: CompilePrdResult = {
      content,
      structure: {
        systemVision: 'A sprint planning workspace for agile delivery teams.',
        systemBoundaries: 'Web application for sprint planning and board management.',
        domainModel: '- Sprint, Task, Team, Board.',
        globalBusinessRules: '- Sprint goals must be approved before execution begins.',
        features: [{
          id: 'F-01',
          name: 'Sprint Board',
          rawContent: '### F-01: Sprint Board\n1. Purpose\nCoordinate sprint work on a shared board.\n10. Acceptance Criteria\n- Teams can move tasks between workflow columns.',
          purpose: 'Coordinate sprint work on a shared board.',
          acceptanceCriteria: ['Teams can move tasks between workflow columns.'],
        }],
        nonFunctional: '- Board updates render within one second.',
        errorHandling: '- Conflicts show retry guidance.',
        deployment: '- Node service with PostgreSQL.',
        definitionOfDone: '- QA review and passing tests are required.',
        outOfScope: '- No mobile app in this release.',
        timelineMilestones: '- Phase 1 delivers backlog import; Phase 2 delivers automation.',
        successCriteria: '- Planning time stays below twenty minutes per sprint.',
        otherSections: {},
      },
      quality: {
        valid: true,
        truncatedLikely: false,
        missingSections: [],
        featureCount: 1,
        issues: [{ severity: 'warning', code: 'excessive_fallback_sections', message: '11/11 sections were auto-generated by the compiler.' }],
        fallbackSections: ['systemBoundaries', 'domainModel', 'globalBusinessRules', 'nonFunctional', 'errorHandling', 'deployment', 'definitionOfDone', 'outOfScope', 'timelineMilestones', 'successCriteria'],
      },
    };

    const compileDocument = vi.fn(() => compiled);
    const contentRefineReviewer = vi.fn(async () => ({ content, model: 'mock/refine', usage: usage(10) }));

    let capturedError: unknown;

    try {
      await finalizeWithCompilerGates({
        initialResult: { content, model: 'mock/initial', usage: usage(80) },
        mode: 'generate',
        language: 'en',
        originalRequest: 'Generate an agile sprint planning PRD.',
        repairReviewer: async () => ({ content, model: 'mock/repair', usage: usage(10) }),
        contentRefineReviewer,
        compileDocument,
      });
    } catch (error) {
      capturedError = error;
    }

    expect(capturedError).toBeInstanceOf(PrdCompilerQualityError);
    expect(capturedError).toMatchObject({
      failureStage: 'compiler_repair',
    });
    expect(contentRefineReviewer).not.toHaveBeenCalled();
    expect(compileDocument).toHaveBeenCalledTimes(3);
  });
});
