/**
 * PRD Content Reviewer - Post-Compiler Content-Quality Review & Refinement
 *
 * Runs AFTER the structural compiler and repair loop. Checks for:
 * - Cross-section repetition (near-identical text in different sections)
 * - Compiler fallback filler (generic text inserted by ensurePrdRequiredSections)
 * - AI-typical phrasing (generic boilerplate language)
 * - Project-specificity (does the section reference actual features/domain?)
 *
 * If issues are found, an AI model rewrites the affected sections
 * with project-specific content derived from the Feature Catalogue.
 */

import type { PRDStructure } from './prdStructure';
import { getTemplateProfile, type RequiredSectionKey } from './prdTemplateIntent';
import { parsePRDToStructure } from './prdParser';
import { assembleStructureToMarkdown } from './prdAssembler';
import { CANONICAL_PRD_HEADINGS } from './prdCompiler';
import { buildTemplateInstruction } from './prdTemplateIntent';

type SupportedLanguage = 'de' | 'en';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface ContentIssue {
  code: string;
  sectionKey: string;
  message: string;
  severity: 'error' | 'warning';
  suggestedAction: 'rewrite' | 'expand' | 'keep';
}

export interface SectionQualityScore {
  specificity: number;   // 0-100: How project-specific is the text?
  depth: number;         // 0-100: How detailed/structured is the text?
  uniqueness: number;    // 0-100: How unique vs. other sections?
  aiPhrasing: number;    // 0-100: 100 = no AI phrases, 0 = full AI boilerplate
  overall: number;       // Weighted average adjusted by aiPhrasing
}

export interface ContentReviewResult {
  issues: ContentIssue[];
  overallScore: number;
  sectionsToRewrite: string[];
  sectionScores: Record<string, SectionQualityScore>;
}

export interface ContentRefineResult {
  content: string;
  structure: PRDStructure;
  reviewResult: ContentReviewResult;
  refined: boolean;
}

// ---------------------------------------------------------------------------
// Section keys used for pairwise comparison (non-feature, non-intro sections)
// ---------------------------------------------------------------------------

const COMPARABLE_SECTION_KEYS: RequiredSectionKey[] = [
  'systemVision',
  'systemBoundaries',
  'domainModel',
  'globalBusinessRules',
  'nonFunctional',
  'errorHandling',
  'deployment',
  'definitionOfDone',
  'outOfScope',
  'timelineMilestones',
  'successCriteria',
];

// ---------------------------------------------------------------------------
// Fallback-pattern detection (matches text generated by buildSectionFallback)
// ---------------------------------------------------------------------------

const FALLBACK_PATTERN_EN = /is explicitly defined for this .+\.\s*(?:Core scope centers on|Context priorities include|This section is concretized).+Statements are implementation-ready, testable,? and binding for this version\./i;
const FALLBACK_PATTERN_DE = /ist f(?:ue|ü)r dieses .+explizit beschrieben\.\s*(?:Kernfokus sind die Feature-Workflows|Der Kontext umfasst|Der Abschnitt wird).+Die Aussagen sind umsetzbar, testbar und f(?:ue|ü)r diese Version verbindlich\./i;

// ---------------------------------------------------------------------------
// AI-typical phrasing patterns (generic filler language)
// ---------------------------------------------------------------------------

const AI_PHRASING_PATTERNS_EN: RegExp[] = [
  /delivers a clearly scoped user capability with an observable outcome/i,
  /defines an independent,? testable workflow/i,
  /implemented as a deterministic functional unit/i,
  /reads and updates only in-scope entities/i,
  /surfaces loading,? success,? and error states.*consistently/i,
  /verifiable by end users directly in the UI without manual reload/i,
  /error paths? (?:for|of) .+ provide clear user feedback and keep state consistent/i,
  /data mutations caused by .+ are observable after execution/i,
];

const AI_PHRASING_PATTERNS_DE: RegExp[] = [
  /liefert einen klar abgegrenzten Nutzerwert mit messbarem Ergebnis/i,
  /beschreibt einen eigenst(?:ae|ä)ndigen,? testbaren Anwendungsfall/i,
  /als implementierbare Funktionseinheit mit eindeutiger Wirkung/i,
  /liest und aktualisiert nur die relevanten Entit(?:ae|ä)ten/i,
  /Oberfl(?:ae|ä)che zeigt Lade-,? Erfolg- und Fehlerzust(?:ae|ä)nde/i,
  /f(?:ue|ü)r einen Nutzer ohne manuelles Nachladen in der UI verifizierbar/i,
  /Fehlerfaelle von .+ liefern klare Nutzerhinweise/i,
  /verursachten Daten(?:ae|ä)nderungen sind nach Ausf(?:ue|ü)hrung nachvollziehbar/i,
];

// ---------------------------------------------------------------------------
// General AI filler phrases (common LLM boilerplate, not compiler-specific)
// ---------------------------------------------------------------------------

const GENERAL_AI_FILLER_PATTERNS: RegExp[] = [
  /\bleverage\s+(?:existing|the)\b/i,
  /\brobust\s+and\s+scalable\b/i,
  /\bseamless(?:ly)?\s+integrat/i,
  /\bintuitive\s+user\s+experience\b/i,
  /\bstate[- ]of[- ]the[- ]art\b/i,
  /\bensure(?:s)?\s+(?:a\s+)?smooth\b/i,
  /\bcomprehensive\s+(?:set|suite|range|solution)\b/i,
  /\bstreamline(?:s|d)?\s+(?:the\s+)?(?:process|workflow|operation)/i,
  /\bnahtlos(?:e[rns]?)?\s+Integr/i,
  /\brobust(?:e[rns]?)?\s+und\s+skalierbar/i,
  /\bintuitive[rns]?\s+Benutzer(?:erfahrung|erlebnis)/i,
  /\bumfassend(?:e[rns]?)?\s+(?:Loesung|L(?:ö|oe)sung)/i,
];

// All AI phrasing patterns combined (for scoring)
const ALL_AI_PATTERNS: RegExp[] = [
  ...AI_PHRASING_PATTERNS_EN,
  ...AI_PHRASING_PATTERNS_DE,
  ...GENERAL_AI_FILLER_PATTERNS,
];

// ---------------------------------------------------------------------------
// Helper: tokenize for Jaccard similarity
// ---------------------------------------------------------------------------

function tokenize(text: string): Set<string> {
  return new Set(
    String(text || '')
      .toLowerCase()
      .replace(/[^\p{L}\p{N}\s]/gu, ' ')
      .split(/\s+/)
      .filter(w => w.length >= 3)
  );
}

function jaccardSimilarity(a: Set<string>, b: Set<string>): number {
  if (a.size === 0 && b.size === 0) return 1;
  if (a.size === 0 || b.size === 0) return 0;
  let intersection = 0;
  for (const token of a) {
    if (b.has(token)) intersection++;
  }
  const union = a.size + b.size - intersection;
  return union > 0 ? intersection / union : 0;
}

// ---------------------------------------------------------------------------
// Helper: extract feature names for specificity check
// ---------------------------------------------------------------------------

function extractProjectTerms(structure: PRDStructure): Set<string> {
  const terms = new Set<string>();
  for (const feature of structure.features || []) {
    const name = String(feature.name || '').toLowerCase();
    for (const word of name.split(/\s+/)) {
      if (word.length >= 4) terms.add(word);
    }
    const id = String(feature.id || '').toLowerCase();
    if (id) terms.add(id);
  }
  // Add terms from system vision (domain-specific keywords)
  const vision = String(structure.systemVision || '').toLowerCase();
  for (const word of vision.split(/[\s,.;:!?]+/)) {
    if (word.length >= 5) terms.add(word);
  }
  return terms;
}

function sectionSpecificityScore(text: string, projectTerms: Set<string>): number {
  if (!text.trim() || projectTerms.size === 0) return 0;
  const words = text.toLowerCase().split(/[\s,.;:!?]+/).filter(w => w.length >= 4);
  if (words.length === 0) return 0;
  const hits = words.filter(w => projectTerms.has(w)).length;
  return Math.min(100, Math.round((hits / words.length) * 400));
}

// ---------------------------------------------------------------------------
// Per-section quality scoring
// ---------------------------------------------------------------------------

const DEFAULT_QUALITY_WEIGHTS = { specificity: 25, uniqueness: 25, depth: 50 };

function scoreSectionQuality(
  text: string,
  key: string,
  projectTerms: Set<string>,
  allSectionTokens: Map<string, Set<string>>,
  weights: { specificity: number; uniqueness: number; depth: number }
): SectionQualityScore {
  // Specificity: reuse existing scorer
  const specificity = sectionSpecificityScore(text, projectTerms);

  // Depth: based on word count + structural markers
  const words = text.split(/\s+/).length;
  const hasBullets = /^[\-\*•]/m.test(text);
  const hasNumbers = /\b\d+\b/.test(text);
  const depth = Math.min(100, Math.round(
    (Math.min(words, 200) / 200) * 60 +
    (hasBullets ? 20 : 0) +
    (hasNumbers ? 20 : 0)
  ));

  // Uniqueness: 100 minus max Jaccard similarity to any other section
  const myTokens = allSectionTokens.get(key);
  let maxSimilarity = 0;
  if (myTokens) {
    for (const [otherKey, otherTokens] of allSectionTokens) {
      if (otherKey === key) continue;
      const sim = jaccardSimilarity(myTokens, otherTokens);
      maxSimilarity = Math.max(maxSimilarity, sim);
    }
  }
  const uniqueness = Math.round((1 - maxSimilarity) * 100);

  // AI phrasing: 100 minus penalty per pattern hit
  const hitCount = ALL_AI_PATTERNS.filter(p => p.test(text)).length;
  const aiPhrasing = Math.max(0, 100 - hitCount * 20);

  // Weighted average of specificity, depth, uniqueness
  const total = weights.specificity + weights.uniqueness + weights.depth;
  const baseOverall = total > 0
    ? Math.round(
        (specificity * weights.specificity +
         depth * weights.depth +
         uniqueness * weights.uniqueness) / total
      )
    : Math.round((specificity + depth + uniqueness) / 3);

  // Apply aiPhrasing as a multiplier (boilerplate reduces overall)
  const overall = Math.round(baseOverall * (aiPhrasing / 100));

  return { specificity, depth, uniqueness, aiPhrasing, overall };
}

// ---------------------------------------------------------------------------
// Core: Deterministic content analysis (no AI needed)
// ---------------------------------------------------------------------------

export function analyzeContentQuality(
  structure: PRDStructure,
  options?: {
    templateCategory?: string;
    fallbackSections?: string[];
  }
): ContentReviewResult {
  const issues: ContentIssue[] = [];
  const sectionsToRewrite = new Set<string>();
  const projectTerms = extractProjectTerms(structure);

  // 1. Check for compiler-generated fallback filler
  const fallbackSections = new Set(options?.fallbackSections || []);

  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text) continue;

    // Detect fallback pattern
    if (FALLBACK_PATTERN_EN.test(text) || FALLBACK_PATTERN_DE.test(text)) {
      issues.push({
        code: 'compiler_fallback_filler',
        sectionKey: key,
        message: `Section "${key}" contains compiler-generated fallback text that is not project-specific.`,
        severity: 'error',
        suggestedAction: 'rewrite',
      });
      sectionsToRewrite.add(key);
    }
  }

  // 2. Cross-section similarity check
  const sectionTexts = new Map<string, { text: string; tokens: Set<string> }>();
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (text.length >= 20) {
      sectionTexts.set(key, { text, tokens: tokenize(text) });
    }
  }

  const keys = Array.from(sectionTexts.keys());
  for (let i = 0; i < keys.length; i++) {
    for (let j = i + 1; j < keys.length; j++) {
      const a = sectionTexts.get(keys[i])!;
      const b = sectionTexts.get(keys[j])!;
      const similarity = jaccardSimilarity(a.tokens, b.tokens);
      if (similarity > 0.7) {
        issues.push({
          code: 'cross_section_repetition',
          sectionKey: keys[i],
          message: `Sections "${keys[i]}" and "${keys[j]}" have near-identical content (${Math.round(similarity * 100)}% similarity).`,
          severity: 'error',
          suggestedAction: 'rewrite',
        });
        sectionsToRewrite.add(keys[i]);
        sectionsToRewrite.add(keys[j]);
      }
    }
  }

  // 3. AI-phrasing detection in non-feature sections (compiler + general)
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text) continue;
    const hitCount = ALL_AI_PATTERNS.filter(p => p.test(text)).length;
    if (hitCount >= 2) {
      issues.push({
        code: 'ai_phrasing_detected',
        sectionKey: key,
        message: `Section "${key}" contains ${hitCount} AI-typical boilerplate phrases.`,
        severity: 'warning',
        suggestedAction: 'rewrite',
      });
      sectionsToRewrite.add(key);
    }
  }

  // 4. AI-phrasing detection in features
  for (const feature of structure.features || []) {
    const featureTexts = [
      feature.purpose, feature.actors, feature.trigger,
      feature.preconditions, feature.postconditions,
      feature.dataImpact, feature.uiImpact,
    ].filter(Boolean).join(' ');

    const hitCount = ALL_AI_PATTERNS.filter(p => p.test(featureTexts)).length;
    if (hitCount >= 3) {
      issues.push({
        code: 'feature_ai_boilerplate',
        sectionKey: `feature:${feature.id}`,
        message: `Feature "${feature.id}: ${feature.name}" has ${hitCount} AI-generated boilerplate fields.`,
        severity: 'warning',
        suggestedAction: 'rewrite',
      });
    }
  }

  // 5. Low specificity check (sections don't reference project terms)
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text || text.length < 40) continue;
    const score = sectionSpecificityScore(text, projectTerms);
    if (score < 10 && !sectionsToRewrite.has(key)) {
      issues.push({
        code: 'low_specificity',
        sectionKey: key,
        message: `Section "${key}" has low project-specificity (score: ${score}/100). It may be generic filler.`,
        severity: 'warning',
        suggestedAction: 'expand',
      });
    }
  }

  // 6. Template-specific checks (via profile)
  const profile = getTemplateProfile(options?.templateCategory);
  if (profile.contentReviewHints?.requiredSectionContent) {
    for (const [sectionKey, patterns] of Object.entries(profile.contentReviewHints.requiredSectionContent)) {
      const text = String((structure as any)[sectionKey] || '').trim();
      if (!text) continue;
      const missing = (patterns as RegExp[]).filter(p => !p.test(text));
      if (missing.length > 0) {
        issues.push({
          code: 'template_content_mismatch',
          sectionKey,
          message: `Section "${sectionKey}" is missing ${missing.length} expected content pattern(s) for template "${profile.category}".`,
          severity: 'warning',
          suggestedAction: 'expand',
        });
      }
    }
  }

  // Per-section quality scoring (reuses `profile` from template-specific checks above)
  const weights = profile.contentReviewHints?.qualityWeights || DEFAULT_QUALITY_WEIGHTS;
  const allTokens = new Map<string, Set<string>>();
  for (const [k, v] of sectionTexts) allTokens.set(k, v.tokens);

  const sectionScores: Record<string, SectionQualityScore> = {};
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text) continue;
    sectionScores[key] = scoreSectionQuality(text, key, projectTerms, allTokens, weights);
  }

  // Overall score: average of section scores (penalty-adjusted)
  const scoreValues = Object.values(sectionScores);
  let score: number;
  if (scoreValues.length > 0) {
    const sum = scoreValues.reduce((acc, s) => acc + s.overall, 0);
    score = Math.round(sum / scoreValues.length);
  } else {
    score = 0;
  }
  // Apply issue penalties on top (errors are structural, not captured by section scores)
  for (const issue of issues) {
    score -= issue.severity === 'error' ? 8 : 2;
  }
  score = Math.max(0, Math.min(100, score));

  return {
    issues,
    overallScore: score,
    sectionsToRewrite: Array.from(sectionsToRewrite),
    sectionScores,
  };
}

// ---------------------------------------------------------------------------
// AI-based content refinement prompt builder
// ---------------------------------------------------------------------------

function buildContentRefinePrompt(params: {
  assembledMarkdown: string;
  structure: PRDStructure;
  issues: ContentIssue[];
  sectionsToRewrite: string[];
  language: SupportedLanguage;
  templateCategory?: string;
}): string {
  const { issues, sectionsToRewrite, language, templateCategory } = params;
  const canonicalHeadings = CANONICAL_PRD_HEADINGS.map(h => `- ## ${h}`).join('\n');
  const templateInstruction = buildTemplateInstruction(templateCategory, language);

  // Build feature context summary for the AI
  const featureSummary = (params.structure.features || [])
    .slice(0, 8)
    .map(f => `- ${f.id}: ${f.name}`)
    .join('\n');

  const visionSnippet = String(params.structure.systemVision || '').trim().slice(0, 300);

  const issueList = issues
    .filter(i => sectionsToRewrite.includes(i.sectionKey))
    .map(i => `- [${i.sectionKey}] ${i.message} → Action: ${i.suggestedAction}`)
    .join('\n');

  const sectionList = sectionsToRewrite.join(', ');

  const langNote = language === 'de'
    ? 'Schreibe ALLE Inhalte auf Deutsch. Behalte nur die englischen H2-Headings bei.'
    : 'Write ALL content in English.';

  return `You are rewriting specific sections of a PRD document to replace generic filler with project-specific content.

PROJECT CONTEXT:
- Vision: ${visionSnippet || '(not available)'}
- Features:
${featureSummary || '(none)'}

ISSUES FOUND:
${issueList}

SECTIONS TO REWRITE: ${sectionList}

CURRENT DOCUMENT:
${params.assembledMarkdown}

INSTRUCTIONS:
1. Rewrite ONLY the sections listed above (${sectionList}).
2. Keep ALL other sections EXACTLY as they are - do not modify them.
3. Make each rewritten section project-specific:
   - Reference actual features by name/ID where appropriate
   - Use concrete, domain-specific language instead of generic filler
   - Each section must have distinct, unique content (no repetition between sections)
4. Section-specific guidance:
   - "definitionOfDone": Write as a concrete checklist (what must be true for release)
   - "outOfScope": List specific exclusions relevant to THIS project
   - "timelineMilestones": Define phases with feature assignments
   - "successCriteria": Define measurable, testable success metrics
5. ${langNote}

STRICT OUTPUT RULES:
- Output the COMPLETE PRD in Markdown (all sections, not just the rewritten ones)
- Use exactly these H2 headings:
${canonicalHeadings}
- ${templateInstruction}
- No meta-commentary, no introductory text
- Start directly with the first ## heading`;
}

// ---------------------------------------------------------------------------
// Public: Full content review + optional AI refinement
// ---------------------------------------------------------------------------

export async function reviewAndRefineContent(options: {
  content: string;
  structure: PRDStructure;
  language: SupportedLanguage;
  templateCategory?: string;
  fallbackSections?: string[];
  refineGenerator?: (prompt: string) => Promise<{ content: string; model: string; usage: any }>;
}): Promise<ContentRefineResult> {
  const { content, structure, language, templateCategory, fallbackSections, refineGenerator } = options;

  // Step 1: Deterministic content analysis
  const reviewResult = analyzeContentQuality(structure, {
    templateCategory,
    fallbackSections,
  });

  // If no issues need rewriting, return as-is
  const rewriteIssues = reviewResult.issues.filter(i => i.suggestedAction === 'rewrite');
  if (rewriteIssues.length === 0 || !refineGenerator) {
    return {
      content,
      structure,
      reviewResult,
      refined: false,
    };
  }

  // Step 2: AI-based refinement
  const refinePrompt = buildContentRefinePrompt({
    assembledMarkdown: content,
    structure,
    issues: reviewResult.issues,
    sectionsToRewrite: reviewResult.sectionsToRewrite,
    language,
    templateCategory,
  });

  try {
    const result = await refineGenerator(refinePrompt);
    const refinedContent = String(result.content || '').trim();

    if (!refinedContent || refinedContent.length < content.length * 0.5) {
      // Refinement produced truncated or empty result - keep original
      return {
        content,
        structure,
        reviewResult,
        refined: false,
      };
    }

    // Step 3: Re-parse to ensure structure is intact
    let refinedStructure: PRDStructure;
    try {
      refinedStructure = parsePRDToStructure(refinedContent);
    } catch {
      // Parse failed - keep original
      return {
        content,
        structure,
        reviewResult,
        refined: false,
      };
    }

    // Validate that features were preserved
    const originalFeatureCount = (structure.features || []).length;
    const refinedFeatureCount = (refinedStructure.features || []).length;
    if (originalFeatureCount > 0 && refinedFeatureCount < originalFeatureCount * 0.8) {
      // Too many features lost during refinement - keep original
      return {
        content,
        structure,
        reviewResult,
        refined: false,
      };
    }

    return {
      content: refinedContent,
      structure: refinedStructure,
      reviewResult,
      refined: true,
    };
  } catch {
    // AI call failed - return original with review results
    return {
      content,
      structure,
      reviewResult,
      refined: false,
    };
  }
}
