/**
 * PRD Content Reviewer - Post-Compiler Content-Quality Review & Refinement
 *
 * Runs AFTER the structural compiler and repair loop. Checks for:
 * - Cross-section repetition (near-identical text in different sections)
 * - Compiler fallback filler (generic text inserted by ensurePrdRequiredSections)
 * - AI-typical phrasing (generic boilerplate language)
 * - Project-specificity (does the section reference actual features/domain?)
 *
 * If issues are found, an AI model rewrites the affected sections
 * with project-specific content derived from the Feature Catalogue.
 */

import type { PRDStructure } from './prdStructure';
import { getTemplateProfile, isGenericFallback, type RequiredSectionKey } from './prdTemplateIntent';
import { tokenizeToSet, jaccardSimilarity } from './prdTextUtils';
import { parsePRDToStructure } from './prdParser';
import { assembleStructureToMarkdown } from './prdAssembler';
import { CANONICAL_PRD_HEADINGS } from './prdCompiler';
import { buildTemplateInstruction } from './prdTemplateIntent';
import { logger } from './logger';

type SupportedLanguage = 'de' | 'en';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface ContentIssue {
  code: string;
  sectionKey: string;
  message: string;
  severity: 'error' | 'warning';
  suggestedAction: 'rewrite' | 'expand' | 'enrich' | 'keep';
}

export interface SectionQualityScore {
  specificity: number;   // 0-100: How project-specific is the text?
  depth: number;         // 0-100: How detailed/structured is the text?
  uniqueness: number;    // 0-100: How unique vs. other sections?
  aiPhrasing: number;    // 0-100: 100 = no AI phrases, 0 = full AI boilerplate
  overall: number;       // Weighted average adjusted by aiPhrasing
}

export interface ContentReviewResult {
  issues: ContentIssue[];
  overallScore: number;
  sectionsToRewrite: string[];
  sectionScores: Record<string, SectionQualityScore>;
}

export interface ContentRefineResult {
  content: string;
  structure: PRDStructure;
  reviewResult: ContentReviewResult;
  refined: boolean;
  enrichedFeatureCount?: number;
}

// ---------------------------------------------------------------------------
// Section keys used for pairwise comparison (non-feature, non-intro sections)
// ---------------------------------------------------------------------------

const COMPARABLE_SECTION_KEYS: RequiredSectionKey[] = [
  'systemVision',
  'systemBoundaries',
  'domainModel',
  'globalBusinessRules',
  'nonFunctional',
  'errorHandling',
  'deployment',
  'definitionOfDone',
  'outOfScope',
  'timelineMilestones',
  'successCriteria',
];

// ---------------------------------------------------------------------------
// Fallback-pattern detection (matches text generated by buildSectionFallback)
// ---------------------------------------------------------------------------

// Compiler fallback pattern detection delegated to isGenericFallback (prdTemplateIntent.ts)

// Template fallback opening-line patterns (match BASE_SECTION_FALLBACKS and
// template-specific sectionFallbacks that may have been baked into the PRD
// during early AI iterations and are no longer tracked as fallback-filled).
const TEMPLATE_FALLBACK_OPENERS: RegExp[] = [
  // definitionOfDone (base)
  /^A feature is complete when:/m,
  /^Ein Feature gilt als abgeschlossen wenn:/m,
  // outOfScope (base + epic)
  /explicitly OUT OF SCOPE for this (?:version|epic)/i,
  /explizit NICHT im Scope/i,
  // timelineMilestones (base + epic)
  /^(?:Die )?Lieferung ist in (?:Phasen|Meilensteine)/m,
  /^Delivery is structured in (?:phases|milestones)/m,
  // successCriteria (base)
  /^(?:Das )?Projekt ist erfolgreich wenn:/m,
  /^The project is successful when:/m,
  // product-launch successCriteria
  /^(?:Der )?Launch is(?:t)? (?:erfolgreich|successful) (?:wenn|when):/m,
  // product-launch timelineMilestones
  /^Launch[- ](?:timeline|Zeitplan):/im,
  // technical nonFunctional opener (very specific p95 pattern)
  /^Performance:\s*API[- ](?:latency|Latenz)\s*p95/m,
];

// ---------------------------------------------------------------------------
// AI-typical phrasing patterns (generic filler language)
// ---------------------------------------------------------------------------

const AI_PHRASING_PATTERNS_EN: RegExp[] = [
  /delivers a clearly scoped user capability with an observable outcome/i,
  /defines an independent,? testable workflow/i,
  /implemented as a deterministic functional unit/i,
  /reads and updates only in-scope entities/i,
  /surfaces loading,? success,? and error states.*consistently/i,
  /verifiable by end users directly in the UI without manual reload/i,
  /error paths? (?:for|of) .+ provide clear user feedback and keep state consistent/i,
  /data mutations caused by .+ are observable after execution/i,
];

const AI_PHRASING_PATTERNS_DE: RegExp[] = [
  /liefert einen klar abgegrenzten Nutzerwert mit messbarem Ergebnis/i,
  /beschreibt einen eigenst(?:ae|ä)ndigen,? testbaren Anwendungsfall/i,
  /als implementierbare Funktionseinheit mit eindeutiger Wirkung/i,
  /liest und aktualisiert nur die relevanten Entit(?:ae|ä)ten/i,
  /Oberfl(?:ae|ä)che zeigt Lade-,? Erfolg- und Fehlerzust(?:ae|ä)nde/i,
  /f(?:ue|ü)r einen Nutzer ohne manuelles Nachladen in der UI verifizierbar/i,
  /Fehlerfaelle von .+ liefern klare Nutzerhinweise/i,
  /verursachten Daten(?:ae|ä)nderungen sind nach Ausf(?:ue|ü)hrung nachvollziehbar/i,
];

// ---------------------------------------------------------------------------
// General AI filler phrases (common LLM boilerplate, not compiler-specific)
// ---------------------------------------------------------------------------

const GENERAL_AI_FILLER_PATTERNS: RegExp[] = [
  /\bleverage\s+(?:existing|the)\b/i,
  /\brobust\s+and\s+scalable\b/i,
  /\bseamless(?:ly)?\s+integrat/i,
  /\bintuitive\s+user\s+experience\b/i,
  /\bstate[- ]of[- ]the[- ]art\b/i,
  /\bensure(?:s)?\s+(?:a\s+)?smooth\b/i,
  /\bcomprehensive\s+(?:set|suite|range|solution)\b/i,
  /\bstreamline(?:s|d)?\s+(?:the\s+)?(?:process|workflow|operation)/i,
  /\bnahtlos(?:e[rns]?)?\s+Integr/i,
  /\brobust(?:e[rns]?)?\s+und\s+skalierbar/i,
  /\bintuitive[rns]?\s+Benutzer(?:erfahrung|erlebnis)/i,
  /\bumfassend(?:e[rns]?)?\s+(?:Loesung|L(?:ö|oe)sung)/i,
];

// All AI phrasing patterns combined (for scoring)
const ALL_AI_PATTERNS: RegExp[] = [
  ...AI_PHRASING_PATTERNS_EN,
  ...AI_PHRASING_PATTERNS_DE,
  ...GENERAL_AI_FILLER_PATTERNS,
];

// tokenizeToSet and jaccardSimilarity imported from prdTextUtils

// ---------------------------------------------------------------------------
// Helper: extract feature names for specificity check
// ---------------------------------------------------------------------------

function extractProjectTerms(structure: PRDStructure): Set<string> {
  const terms = new Set<string>();
  for (const feature of structure.features || []) {
    const name = String(feature.name || '').toLowerCase();
    for (const word of name.split(/\s+/)) {
      if (word.length >= 4) terms.add(word);
    }
    const id = String(feature.id || '').toLowerCase();
    if (id) terms.add(id);
  }
  // Add terms from system vision (domain-specific keywords)
  const vision = String(structure.systemVision || '').toLowerCase();
  for (const word of vision.split(/[\s,.;:!?]+/)) {
    if (word.length >= 5) terms.add(word);
  }
  return terms;
}

function sectionSpecificityScore(text: string, projectTerms: Set<string>): number {
  if (!text.trim() || projectTerms.size === 0) return 0;
  const words = text.toLowerCase().split(/[\s,.;:!?]+/).filter(w => w.length >= 4);
  if (words.length === 0) return 0;
  const hits = words.filter(w => projectTerms.has(w)).length;
  return Math.min(100, Math.round((hits / words.length) * 400));
}

// ---------------------------------------------------------------------------
// Per-section quality scoring
// ---------------------------------------------------------------------------

const DEFAULT_QUALITY_WEIGHTS = { specificity: 25, uniqueness: 25, depth: 50 };

function scoreSectionQuality(
  text: string,
  key: string,
  projectTerms: Set<string>,
  allSectionTokens: Map<string, Set<string>>,
  weights: { specificity: number; uniqueness: number; depth: number }
): SectionQualityScore {
  // Specificity: reuse existing scorer
  const specificity = sectionSpecificityScore(text, projectTerms);

  // Depth: based on word count + structural markers
  const words = text.split(/\s+/).length;
  const hasBullets = /^[\-\*•]/m.test(text);
  const hasNumbers = /\b\d+\b/.test(text);
  const depth = Math.min(100, Math.round(
    (Math.min(words, 200) / 200) * 60 +
    (hasBullets ? 20 : 0) +
    (hasNumbers ? 20 : 0)
  ));

  // Uniqueness: 100 minus max Jaccard similarity to any other section
  const myTokens = allSectionTokens.get(key);
  let maxSimilarity = 0;
  if (myTokens) {
    for (const [otherKey, otherTokens] of allSectionTokens) {
      if (otherKey === key) continue;
      const sim = jaccardSimilarity(myTokens, otherTokens);
      maxSimilarity = Math.max(maxSimilarity, sim);
    }
  }
  const uniqueness = Math.round((1 - maxSimilarity) * 100);

  // AI phrasing: 100 minus penalty per pattern hit
  const hitCount = ALL_AI_PATTERNS.filter(p => p.test(text)).length;
  const aiPhrasing = Math.max(0, 100 - hitCount * 20);

  // Weighted average of specificity, depth, uniqueness
  const total = weights.specificity + weights.uniqueness + weights.depth;
  const baseOverall = total > 0
    ? Math.round(
        (specificity * weights.specificity +
         depth * weights.depth +
         uniqueness * weights.uniqueness) / total
      )
    : Math.round((specificity + depth + uniqueness) / 3);

  // Apply aiPhrasing as a multiplier (boilerplate reduces overall)
  const overall = Math.round(baseOverall * (aiPhrasing / 100));

  return { specificity, depth, uniqueness, aiPhrasing, overall };
}

// ---------------------------------------------------------------------------
// Core: Deterministic content analysis (no AI needed)
// ---------------------------------------------------------------------------

export function analyzeContentQuality(
  structure: PRDStructure,
  options?: {
    templateCategory?: string;
    fallbackSections?: string[];
  }
): ContentReviewResult {
  const issues: ContentIssue[] = [];
  const sectionsToRewrite = new Set<string>();
  const projectTerms = extractProjectTerms(structure);

  // 1. Check for compiler-generated fallback filler
  // Use the explicit list of fallback-filled sections (from ensurePrdRequiredSections
  // and ensurePrdSectionDepth) as primary signal; regex as secondary safety net.
  const knownFallbackSections = new Set(options?.fallbackSections || []);
  const sectionLabelToKey = new Map<string, RequiredSectionKey>();
  for (const key of COMPARABLE_SECTION_KEYS) {
    // Match both the section key and common heading labels to the key
    sectionLabelToKey.set(key, key);
  }

  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text) continue;

    // Primary: check if this section was explicitly filled by fallback pipeline
    const isFallbackFilled = knownFallbackSections.has(key)
      || [...knownFallbackSections].some(label =>
        label.toLowerCase().replace(/[^a-z]/g, '').includes(key.toLowerCase().replace(/[^a-z]/g, ''))
        || key.toLowerCase().replace(/[^a-z]/g, '').includes(label.toLowerCase().replace(/[^a-z]/g, ''))
      );

    // Secondary: regex pattern matching for old-format fallbacks (single source of truth)
    const matchesRegex = isGenericFallback(text);

    // Tertiary: template fallback opening-line patterns (catches fallback text
    // baked in during early AI iterations that is no longer tracked explicitly)
    const matchesTemplateOpener = TEMPLATE_FALLBACK_OPENERS.some(p => p.test(text));

    if (isFallbackFilled || matchesRegex || matchesTemplateOpener) {
      issues.push({
        code: 'compiler_fallback_filler',
        sectionKey: key,
        message: `Section "${key}" contains compiler-generated fallback text that is not project-specific.`,
        severity: 'error',
        suggestedAction: 'rewrite',
      });
      sectionsToRewrite.add(key);
    }
  }

  // 2. Cross-section similarity check
  const sectionTexts = new Map<string, { text: string; tokens: Set<string> }>();
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (text.length >= 20) {
      sectionTexts.set(key, { text, tokens: tokenizeToSet(text) });
    }
  }

  const keys = Array.from(sectionTexts.keys());
  for (let i = 0; i < keys.length; i++) {
    for (let j = i + 1; j < keys.length; j++) {
      const a = sectionTexts.get(keys[i])!;
      const b = sectionTexts.get(keys[j])!;
      const similarity = jaccardSimilarity(a.tokens, b.tokens);
      if (similarity > 0.7) {
        issues.push({
          code: 'cross_section_repetition',
          sectionKey: keys[i],
          message: `Sections "${keys[i]}" and "${keys[j]}" have near-identical content (${Math.round(similarity * 100)}% similarity).`,
          severity: 'error',
          suggestedAction: 'rewrite',
        });
        sectionsToRewrite.add(keys[i]);
        sectionsToRewrite.add(keys[j]);
      }
    }
  }

  // 3. AI-phrasing detection in non-feature sections (compiler + general)
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text) continue;
    const hitCount = ALL_AI_PATTERNS.filter(p => p.test(text)).length;
    if (hitCount >= 2) {
      issues.push({
        code: 'ai_phrasing_detected',
        sectionKey: key,
        message: `Section "${key}" contains ${hitCount} AI-typical boilerplate phrases.`,
        severity: 'warning',
        suggestedAction: 'rewrite',
      });
      sectionsToRewrite.add(key);
    }
  }

  // 4. AI-phrasing detection in features
  for (const feature of structure.features || []) {
    const featureTexts = [
      feature.purpose, feature.actors, feature.trigger,
      feature.preconditions, feature.postconditions,
      feature.dataImpact, feature.uiImpact,
    ].filter(Boolean).join(' ');

    const hitCount = ALL_AI_PATTERNS.filter(p => p.test(featureTexts)).length;
    if (hitCount >= 3) {
      issues.push({
        code: 'feature_ai_boilerplate',
        sectionKey: `feature:${feature.id}`,
        message: `Feature "${feature.id}: ${feature.name}" has ${hitCount} AI-generated boilerplate fields.`,
        severity: 'warning',
        suggestedAction: 'rewrite',
      });
    }
  }

  // 5. Feature field incompleteness — detect features with mostly empty structured fields
  const FEATURE_FIELDS = [
    'purpose', 'actors', 'trigger', 'preconditions', 'mainFlow',
    'alternateFlows', 'postconditions', 'dataImpact', 'uiImpact', 'acceptanceCriteria',
  ] as const;
  const INCOMPLETE_FIELD_THRESHOLD = 5;

  for (const feature of structure.features || []) {
    const missingFields: string[] = [];
    for (const field of FEATURE_FIELDS) {
      const value = (feature as any)[field];
      const filled = Array.isArray(value) ? value.length > 0 : Boolean(value && String(value).trim());
      if (!filled) missingFields.push(field);
    }
    if (missingFields.length >= INCOMPLETE_FIELD_THRESHOLD) {
      issues.push({
        code: 'feature_fields_incomplete',
        sectionKey: `feature:${feature.id}`,
        message: `Feature "${feature.id}: ${feature.name}" has ${FEATURE_FIELDS.length - missingFields.length}/${FEATURE_FIELDS.length} fields filled. Missing: ${missingFields.join(', ')}`,
        severity: 'warning',
        suggestedAction: 'enrich',
      });
    }
  }

  // 5b. Feature content shallow — fields are filled but lack substance
  for (const feature of structure.features || []) {
    const featureNameLower = (feature.name || '').toLowerCase().replace(/[^a-z0-9\s]/g, '').trim();
    const featureNameWords = new Set(featureNameLower.split(/\s+/).filter(w => w.length >= 3));
    let substantialCount = 0;
    const shallowFields: string[] = [];

    for (const field of FEATURE_FIELDS) {
      const value = (feature as any)[field];
      let isSubstantial = false;

      if (Array.isArray(value)) {
        const minItems = field === 'mainFlow' ? 3 : field === 'acceptanceCriteria' ? 2 : 1;
        const meaningful = value.filter((entry: string) => String(entry || '').trim().length >= 10);
        isSubstantial = meaningful.length >= minItems;
      } else if (typeof value === 'string') {
        const text = value.trim();
        const minLen = field === 'purpose' ? 30 : 20;
        if (text.length >= minLen) {
          const textWords = new Set(text.toLowerCase().replace(/[^a-z0-9\s]/g, '').split(/\s+/).filter(w => w.length >= 3));
          const overlap = [...featureNameWords].filter(w => textWords.has(w)).length;
          const echoRatio = featureNameWords.size > 0 ? overlap / featureNameWords.size : 0;
          isSubstantial = !(echoRatio > 0.8 && text.length < 60);
        }
      }

      if (isSubstantial) {
        substantialCount++;
      } else {
        const val = (feature as any)[field];
        const filled = Array.isArray(val) ? val.length > 0 : Boolean(val && String(val).trim());
        if (filled) shallowFields.push(field);
      }
    }

    if (substantialCount < 4 && shallowFields.length > 0) {
      issues.push({
        code: 'feature_content_shallow',
        sectionKey: `feature:${feature.id}`,
        message: `Feature "${feature.id}: ${feature.name}" has ${substantialCount}/10 substantial fields. Shallow: ${shallowFields.join(', ')}`,
        severity: 'warning',
        suggestedAction: 'enrich',
      });
    }
  }

  // 6. Low specificity check (sections don't reference project terms)
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text || text.length < 40) continue;
    const score = sectionSpecificityScore(text, projectTerms);
    if (score < 20 && !sectionsToRewrite.has(key)) {
      issues.push({
        code: 'low_specificity',
        sectionKey: key,
        message: `Section "${key}" has low project-specificity (score: ${score}/100). It may be generic filler.`,
        severity: 'warning',
        suggestedAction: 'expand',
      });
    }
  }

  // 7. Template-specific checks (via profile)
  const profile = getTemplateProfile(options?.templateCategory);
  if (profile.contentReviewHints?.requiredSectionContent) {
    for (const [sectionKey, patterns] of Object.entries(profile.contentReviewHints.requiredSectionContent)) {
      const text = String((structure as any)[sectionKey] || '').trim();
      if (!text) continue;
      const missing = (patterns as RegExp[]).filter(p => !p.test(text));
      if (missing.length > 0) {
        issues.push({
          code: 'template_content_mismatch',
          sectionKey,
          message: `Section "${sectionKey}" is missing ${missing.length} expected content pattern(s) for template "${profile.category}".`,
          severity: 'warning',
          suggestedAction: 'expand',
        });
      }
    }
  }

  // Per-section quality scoring (reuses `profile` from template-specific checks above)
  const weights = profile.contentReviewHints?.qualityWeights || DEFAULT_QUALITY_WEIGHTS;
  const allTokens = new Map<string, Set<string>>();
  for (const [k, v] of sectionTexts) allTokens.set(k, v.tokens);

  const sectionScores: Record<string, SectionQualityScore> = {};
  for (const key of COMPARABLE_SECTION_KEYS) {
    const text = String((structure as any)[key] || '').trim();
    if (!text) continue;
    sectionScores[key] = scoreSectionQuality(text, key, projectTerms, allTokens, weights);
  }

  // Overall score: average of section scores (penalty-adjusted)
  const scoreValues = Object.values(sectionScores);
  let score: number;
  if (scoreValues.length > 0) {
    const sum = scoreValues.reduce((acc, s) => acc + s.overall, 0);
    score = Math.round(sum / scoreValues.length);
  } else {
    score = 0;
  }
  // Apply issue penalties on top (errors are structural, not captured by section scores)
  for (const issue of issues) {
    score -= issue.severity === 'error' ? 8 : 2;
  }
  score = Math.max(0, Math.min(100, score));

  return {
    issues,
    overallScore: score,
    sectionsToRewrite: Array.from(sectionsToRewrite),
    sectionScores,
  };
}

// ---------------------------------------------------------------------------
// Feature enrichment: build prompt to fill empty feature fields via AI
// ---------------------------------------------------------------------------

const ENRICHABLE_FIELDS = [
  'purpose', 'actors', 'trigger', 'preconditions', 'mainFlow',
  'alternateFlows', 'postconditions', 'dataImpact', 'uiImpact', 'acceptanceCriteria',
] as const;

export function buildFeatureEnrichPrompt(params: {
  features: Array<{ id: string; name: string; rawContent?: string; missingFields: string[] }>;
  projectContext: {
    systemVision: string;
    domainModel: string;
    otherFeatures: Array<{ id: string; name: string }>;
  };
  language: SupportedLanguage;
}): string {
  const { features, projectContext, language } = params;
  const langNote = language === 'de'
    ? 'Schreibe ALLE Inhalte auf Deutsch. Verwende projektspezifische Begriffe aus dem Kontext.'
    : 'Write ALL content in English. Use project-specific terms from the context.';

  const featureBlocks = features.map(f => {
    const rawSnippet = f.rawContent
      ? `\nRaw description:\n${f.rawContent.slice(0, 800)}`
      : '';
    return `### ${f.id}: ${f.name}
Missing fields: ${f.missingFields.join(', ')}${rawSnippet}`;
  }).join('\n\n');

  const otherFeatureList = projectContext.otherFeatures
    .slice(0, 10)
    .map(f => `- ${f.id}: ${f.name}`)
    .join('\n');

  return `You are enriching incomplete PRD feature specifications with project-specific content.

PROJECT CONTEXT:
- Vision: ${projectContext.systemVision.slice(0, 400)}
- Domain Model: ${projectContext.domainModel.slice(0, 400)}
- Other features in this project:
${otherFeatureList}

FEATURES TO ENRICH:

${featureBlocks}

INSTRUCTIONS:
1. For each feature, generate ONLY the missing fields listed above.
2. ${langNote}
3. Each field must be project-specific — reference the actual feature, its domain, and its interactions with other features.
4. Do NOT generate generic template text. Every sentence must be specific to this exact feature in this exact project.
5. Field format rules:
   - purpose: 1-2 sentences describing what this feature achieves
   - actors: Who triggers and who is affected (e.g., "User", "Admin", "Backend Service")
   - trigger: What action or event starts this feature
   - preconditions: What must be true before this feature can execute
   - mainFlow: Numbered steps (1. ..., 2. ..., etc.) — 3-6 steps
   - alternateFlows: 1-2 error/edge-case paths
   - postconditions: What state exists after successful completion
   - dataImpact: Which data entities are read, created, updated, or deleted
   - uiImpact: How the UI changes (components, states, visual feedback)
   - acceptanceCriteria: 2-4 testable criteria (use checkmark format: "- [ ] ...")

OUTPUT FORMAT:
For each feature, output a labeled block:

=== F-XX: FeatureName ===
**purpose**: ...
**actors**: ...
**trigger**: ...
**mainFlow**:
1. ...
2. ...
**acceptanceCriteria**:
- [ ] ...
- [ ] ...

Only output the fields that were listed as missing. Do NOT output fields that already exist.`;
}

export function parseFeatureEnrichResponse(
  response: string,
  featureIds: string[]
): Map<string, Record<string, string | string[]>> {
  const enriched = new Map<string, Record<string, string | string[]>>();
  const allowedIds = new Set(featureIds.map(id => id.toUpperCase()));
  const featureBlocks = response.split(/^===\s*/m).filter(Boolean);

  for (const block of featureBlocks) {
    // Match feature ID from block header
    const idMatch = block.match(/^(F-\d+)/i);
    if (!idMatch) continue;
    const fId = idMatch[1].toUpperCase();
    if (!allowedIds.has(fId)) continue;

    const fields: Record<string, string | string[]> = {};

    for (const fieldName of ENRICHABLE_FIELDS) {
      // Match **fieldName**: content or **fieldName**:\n content
      const pattern = new RegExp(
        `\\*\\*${fieldName}\\*\\*:\\s*([\\s\\S]*?)(?=\\*\\*(?:${ENRICHABLE_FIELDS.join('|')})\\*\\*:|===\\s*F-|$)`,
        'i'
      );
      const match = block.match(pattern);
      if (!match) continue;

      const raw = match[1].trim();
      if (!raw) continue;

      // Array fields: mainFlow, alternateFlows, acceptanceCriteria
      if (fieldName === 'mainFlow' || fieldName === 'alternateFlows' || fieldName === 'acceptanceCriteria') {
        const steps = raw
          .split(/\n/)
          .map(line => line.replace(/^\d+\.\s*/, '').replace(/^-\s*\[.\]\s*/, '').replace(/^-\s*/, '').trim())
          .filter(line => line.length > 5);
        if (steps.length > 0) fields[fieldName] = steps;
      } else {
        fields[fieldName] = raw;
      }
    }

    if (Object.keys(fields).length > 0) {
      enriched.set(fId, fields);
    }
  }

  return enriched;
}

// ---------------------------------------------------------------------------
// AI-based content refinement prompt builder
// ---------------------------------------------------------------------------

function buildContentRefinePrompt(params: {
  assembledMarkdown: string;
  structure: PRDStructure;
  issues: ContentIssue[];
  sectionsToRewrite: string[];
  language: SupportedLanguage;
  templateCategory?: string;
}): string {
  const { issues, sectionsToRewrite, language, templateCategory } = params;
  const canonicalHeadings = CANONICAL_PRD_HEADINGS.map(h => `- ## ${h}`).join('\n');
  const templateInstruction = buildTemplateInstruction(templateCategory, language);

  // Build feature context summary for the AI
  const featureSummary = (params.structure.features || [])
    .slice(0, 8)
    .map(f => `- ${f.id}: ${f.name}`)
    .join('\n');

  const visionSnippet = String(params.structure.systemVision || '').trim().slice(0, 300);

  const issueList = issues
    .filter(i => sectionsToRewrite.includes(i.sectionKey))
    .map(i => `- [${i.sectionKey}] ${i.message} → Action: ${i.suggestedAction}`)
    .join('\n');

  const sectionList = sectionsToRewrite.join(', ');

  const langNote = language === 'de'
    ? 'Schreibe ALLE Inhalte auf Deutsch. Behalte nur die englischen H2-Headings bei.'
    : 'Write ALL content in English.';

  return `You are rewriting specific sections of a PRD document to replace generic filler with project-specific content.

PROJECT CONTEXT:
- Vision: ${visionSnippet || '(not available)'}
- Features:
${featureSummary || '(none)'}

ISSUES FOUND:
${issueList}

SECTIONS TO REWRITE: ${sectionList}

CURRENT DOCUMENT:
${params.assembledMarkdown}

INSTRUCTIONS:
1. Rewrite ONLY the sections listed above (${sectionList}).
2. Keep ALL other sections EXACTLY as they are - do not modify them.
3. Make each rewritten section project-specific:
   - Reference actual features by name/ID where appropriate
   - Use concrete, domain-specific language instead of generic filler
   - Each section must have distinct, unique content (no repetition between sections)
4. Section-specific guidance:
   - "definitionOfDone": Write as a concrete checklist (what must be true for release)
   - "outOfScope": List specific exclusions relevant to THIS project
   - "timelineMilestones": Define phases with feature assignments
   - "successCriteria": Define measurable, testable success metrics
5. ${langNote}

STRICT OUTPUT RULES:
- Output the COMPLETE PRD in Markdown (all sections, not just the rewritten ones)
- Use exactly these H2 headings:
${canonicalHeadings}
- ${templateInstruction}
- No meta-commentary, no introductory text
- Start directly with the first ## heading`;
}

// ---------------------------------------------------------------------------
// Public: Full content review + optional AI refinement
// ---------------------------------------------------------------------------

export async function reviewAndRefineContent(options: {
  content: string;
  structure: PRDStructure;
  language: SupportedLanguage;
  templateCategory?: string;
  fallbackSections?: string[];
  refineGenerator?: (prompt: string) => Promise<{ content: string; model: string; usage: any }>;
}): Promise<ContentRefineResult> {
  const { language, templateCategory, fallbackSections, refineGenerator } = options;
  let { content, structure } = options;
  let enrichedFeatureCount = 0;

  // Step 1: Deterministic content analysis
  const reviewResult = analyzeContentQuality(structure, {
    templateCategory,
    fallbackSections,
  });

  if (!refineGenerator) {
    return { content, structure, reviewResult, refined: false };
  }

  // Step 2: Feature enrichment — fill incomplete OR shallow features via targeted AI call
  const enrichIssues = reviewResult.issues.filter(i =>
    i.code === 'feature_fields_incomplete' || i.code === 'feature_content_shallow'
  );
  if (enrichIssues.length > 0) {
    const featuresToEnrich = enrichIssues.map(issue => {
      const fId = issue.sectionKey.replace('feature:', '');
      const feature = (structure.features || []).find(f => f.id === fId);
      // For incomplete: extract missing fields from message
      const missingMatch = issue.message.match(/Missing: (.+)$/);
      // For shallow: extract shallow fields from message
      const shallowMatch = issue.message.match(/Shallow: (.+)$/);
      const missingFields = missingMatch
        ? missingMatch[1].split(', ').map(s => s.trim())
        : shallowMatch
          ? shallowMatch[1].split(', ').map(s => s.trim())
          : [];
      return {
        id: fId,
        name: feature?.name || fId,
        rawContent: feature?.rawContent,
        missingFields,
      };
    }).filter(f => f.missingFields.length > 0);

    if (featuresToEnrich.length > 0) {
      const enrichPrompt = buildFeatureEnrichPrompt({
        features: featuresToEnrich,
        projectContext: {
          systemVision: String(structure.systemVision || '').trim(),
          domainModel: String(structure.domainModel || '').trim(),
          otherFeatures: (structure.features || []).map(f => ({ id: f.id, name: f.name })),
        },
        language,
      });

      let enrichmentAttempts = 0;
      const MAX_ENRICHMENT_ATTEMPTS = 2;
      let enrichmentSucceeded = false;

      while (enrichmentAttempts < MAX_ENRICHMENT_ATTEMPTS && !enrichmentSucceeded) {
        enrichmentAttempts++;
        try {
          const enrichResult = await refineGenerator(enrichPrompt);
          const enrichResponse = String(enrichResult.content || '').trim();
          if (enrichResponse.length > 50) {
            const enriched = parseFeatureEnrichResponse(
              enrichResponse,
              featuresToEnrich.map(f => f.id)
            );

            // Merge enriched fields into structure
            // For shallow features: also replace thin existing content if enrichment is longer
            const shallowFeatureIds = new Set(
              enrichIssues.filter(i => i.code === 'feature_content_shallow').map(i => i.sectionKey.replace('feature:', ''))
            );
            if (enriched.size > 0) {
              const updatedFeatures = (structure.features || []).map(feature => {
                const fields = enriched.get(feature.id);
                if (!fields) return feature;
                const updated = { ...feature };
                const isShallow = shallowFeatureIds.has(feature.id);
                for (const [key, value] of Object.entries(fields)) {
                  const existing = (updated as any)[key];
                  const isEmpty = Array.isArray(existing)
                    ? existing.length === 0
                    : !existing || !String(existing).trim();
                  // For shallow features: also replace if enrichment is substantially longer
                  const shouldReplace = isEmpty || (isShallow && (() => {
                    const existingLen = Array.isArray(existing) ? existing.join(' ').length : String(existing || '').length;
                    const newLen = Array.isArray(value) ? (value as string[]).join(' ').length : String(value || '').length;
                    return newLen > existingLen * 1.5; // Replace if enrichment is 50%+ longer
                  })());
                  if (shouldReplace) {
                    (updated as any)[key] = value;
                    enrichedFeatureCount++;
                  }
                }
                return updated;
              });
              structure = { ...structure, features: updatedFeatures };
              content = assembleStructureToMarkdown(structure);
              enrichmentSucceeded = true;
            }
          }
        } catch (err) {
          logger.warn(`Feature enrichment attempt ${enrichmentAttempts}/${MAX_ENRICHMENT_ATTEMPTS} failed`, {
            error: err instanceof Error ? err.message : 'Unknown error',
            stage: 'feature_enrichment',
            attempt: enrichmentAttempts,
          });
        }
      }

      if (!enrichmentSucceeded && featuresToEnrich.length > 0) {
        reviewResult.issues.push({
          code: 'feature_enrichment_failed',
          sectionKey: 'features',
          message: `AI feature enrichment failed after ${enrichmentAttempts} attempts. ${featuresToEnrich.length} feature(s) may have incomplete fields.`,
          severity: 'warning',
          suggestedAction: 'enrich',
        });
      }
    }
  }

  // Step 3: Section refinement — rewrite fallback-filled or boilerplate sections
  const rewriteIssues = reviewResult.issues.filter(i => i.suggestedAction === 'rewrite');
  if (rewriteIssues.length === 0) {
    return { content, structure, reviewResult, refined: enrichedFeatureCount > 0, enrichedFeatureCount };
  }

  const refinePrompt = buildContentRefinePrompt({
    assembledMarkdown: content,
    structure,
    issues: reviewResult.issues,
    sectionsToRewrite: reviewResult.sectionsToRewrite,
    language,
    templateCategory,
  });

  try {
    const result = await refineGenerator(refinePrompt);
    const refinedContent = String(result.content || '').trim();

    if (!refinedContent || refinedContent.length < content.length * 0.5) {
      return { content, structure, reviewResult, refined: enrichedFeatureCount > 0, enrichedFeatureCount };
    }

    let refinedStructure: PRDStructure;
    try {
      refinedStructure = parsePRDToStructure(refinedContent);
    } catch {
      return { content, structure, reviewResult, refined: enrichedFeatureCount > 0, enrichedFeatureCount };
    }

    // Validate that features were preserved (strict: max 5% loss)
    const originalFeatureCount = (structure.features || []).length;
    const refinedFeatureCount = (refinedStructure.features || []).length;
    if (originalFeatureCount > 0 && refinedFeatureCount < originalFeatureCount * 0.95) {
      return { content, structure, reviewResult, refined: enrichedFeatureCount > 0, enrichedFeatureCount };
    }

    // Validate feature field completeness wasn't degraded
    if (originalFeatureCount > 0 && refinedFeatureCount >= originalFeatureCount * 0.95) {
      const countFilledFields = (features: any[]) => features.reduce((sum, f) => {
        return sum + ENRICHABLE_FIELDS.filter(field => {
          const v = (f as any)[field];
          return Array.isArray(v) ? v.length > 0 : Boolean(v && String(v).trim());
        }).length;
      }, 0);
      const originalFilled = countFilledFields(structure.features || []);
      const refinedFilled = countFilledFields(refinedStructure.features || []);
      if (originalFilled > 0 && refinedFilled < originalFilled * 0.9) {
        return { content, structure, reviewResult, refined: enrichedFeatureCount > 0, enrichedFeatureCount };
      }
    }

    return {
      content: refinedContent,
      structure: refinedStructure,
      reviewResult,
      refined: true,
      enrichedFeatureCount,
    };
  } catch {
    return { content, structure, reviewResult, refined: enrichedFeatureCount > 0, enrichedFeatureCount };
  }
}
